language: csharp
mono: none
dist: focal
dotnet: 6.0.202
branches:
  only:
    - master

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - sudo apt-get update
  - sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git
  - sudo rm -rf /opt/pyenv
  - curl https://pyenv.run | bash
  - export PATH="$HOME/.pyenv/bin:$PATH"
  - eval "$(pyenv init -)"
  - eval "$(pyenv virtualenv-init -)"
  - pyenv install 3.8.0
  - pyenv glo

# [START travis_deploy]
deploy:
    provider: gae
    # Skip cleanup so api_key.py and vendored dependencies are still there
    skip_cleanup: true
    keyfile: devopsene23-351ad42ddd85.json
    project: account-418401
    version: service-demo
    default: true
    on:
        all_branches: true
# [END travis_deploy]